Added health-check implementation and description
systelab/seed-dotnet pull request #19
Opened 2019-08-09 10:36 UTC by orozluk

2019-08-26 05:43 UTC, apenalver2 requested changes
Can we include in the .gitignore file the test project obj?

2019-08-30 10:28 UTC, PacmanForever commented on src/main/Healthchecks/ExampleHealthCheck.cs
> +        public Task<HealthCheckResult> CheckHealthAsync(
If the class name is "ExampleHealthCheck", the method can rename to "CheckAsync", "GoAsync" or "ExecuteAsync".

2019-08-30 10:28 UTC, PacmanForever commented on src/main/Healthchecks/ExampleHealthCheck.cs
> +            if (healthCheckResultHealthy)
Merge previous and this line.

2019-08-30 10:55 UTC, orozluk commented on src/main/Healthchecks/ExampleHealthCheck.cs
> +        public Task<HealthCheckResult> CheckHealthAsync(
It is just an example class. In any case. CheckAsync would be the best option.

2019-08-30 10:56 UTC, orozluk commented on src/main/Healthchecks/ExampleHealthCheck.cs
> +            if (healthCheckResultHealthy)
Again, is an empty example health check. If in the future it has more content that would be improved

2019-08-30 11:00 UTC, orozluk commented
> Can we include in the .gitignore file the test project obj?

@apenalver2  included in latest commit

2019-09-13 14:02 UTC, merged